### PR TITLE
ncbi_egapx: form seems to work and generates what looks like valid yaml

### PR DESCRIPTION
**Pull request by fubar2**
needs tests but cannot even run let alone test here - no machine with 120GB or 31 cores -  because of the resource requirements baked into the docker image
 
image

### CODE REVIEW

**Review by richard-burhans — APPROVED** [review]
Looks good!

**Comment by richard-burhans** [comment]
Attention: deployment failure!

https://github.com/richard-burhans/galaxytools/actions/runs/10781909881

**Comment by nekrut** [comment]
@fubar2 or @richard-burhans = we need to add an option that would allow EGAPx to take a file with Protein FASTA as annotation source (see https://github.com/ncbi/egapx?tab=readme-ov-file#input-data-format)

**Comment by fubar2** [comment]
> would allow EGAPx to take a file with Protein FASTA 

@nekrut: Trivial enough to add another form input, but need to understand when that might be useful.

Probably a good idea if you can find a protein annotation file that is _**totally independent of the NCBI**_. 

Unfortunately if an NCBI protein fasta exists for this taxon, it is an output from running the internal NCBI egapx version AFAIK, so feeding that back to egapx for predicting proteins will probably give invalid results because of the circular information dependencies.

**Comment by marco91sol** [comment]
I believe we can implement this and run some tests to compare the results with and without the additional protein FASTA and HMM files. EGAPx treats these as optional parameters:
image
However, the challenge is that the taxid-protein set is not available for all taxa (I've already contacted the CGR group for more information). For instance, I encountered this issue while testing on sharks, where the taxid wasn't connected to any protein set.

**Pull request merged**
